#!/bin/sh
usage() {
  echo "usage: bump-version <version-id>"
}

if [ $# -ne 1 ]; then
  usage
  exit 1
fi

if ! sed 's/"AMOUTREACH_VERSION=.*$/AMOUTREACH_VERSION='$1'/g' amoutreach-version > .amoutreach-version.new; then
  echo "Could not reaplce AMOUTREACH_VERSION variable." > $2
  exit 2
fi

mv .amoutreach-version.new amoutreach-version
git add amoutreach-version
git commit -m "Bumped version number to $1" amoutreach-version
