MANDRILL_USERNAME: aaron@amoutreach.com
MANDRILL_API_KEY: k4ONwYHIxGjL-_njR5Af1Q
MAILCHIMP_API_KEY: 563637df08d1bfb03f92bb0cf00edb0a-us3
MAILCHIMP_LIST_ID: e266af40f9
ADMIN_NAME: Bubba Admin
ADMIN_EMAIL: bubba@amoutreach.com
ADMIN_PASSWORD: '!nimdAabbuB?'
ROLES: [admin, user]
EMAIL_ADDRESS: info@amoutreach.com
DOMAIN: amoutreach.com
AMOUTREACH_DEV_DB_DATABASE: amoutreach_development
AMOUTREACH_DEV_DB_HOST: localhost
AMOUTREACH_DEV_DB_PORT: 3306
AMOUTREACH_DEV_DB_USER: howl
AMOUTREACH_DEV_DB_PASSWORD: welovebubbles