# Add account credentials and API keys here.
# See http://railsapps.github.io/rails-environment-variables.html
# This file should be listed in .gitignore to keep your settings secret!
# Each entry sets a local environment variable and overrides ENV variables in the Unix shell.
# For example, setting:
# GMAIL_USERNAME: Your_Gmail_Username
# makes 'Your_Gmail_Username' available as ENV["GMAIL_USERNAME"]
# Add application configuration variables here, as shown below.
#
MANDRILL_USERNAME: aaron@amoutreach.com
MANDRILL_API_KEY: k4ONwYHIxGjL-_njR5Af1Q
MAILCHIMP_API_KEY: 563637df08d1bfb03f92bb0cf00edb0a-us3
MAILCHIMP_LIST_ID: e266af40f9
ADMIN_NAME: Bubba Admin
ADMIN_EMAIL: bubba@amoutreach.com
ADMIN_PASSWORD: '!nimdAabbuB?'
ROLES: [admin, user]
EMAIL_ADDRESS: info@amoutreach.com
DOMAIN: amoutreach.com
