development:
  adapter: mysql2
  encoding: utf8

  database: <%= ENV['AMOUTREACH_DEV_DB_DATABASE'] || 'amoutreach_development' %>
  pool: 5
  username: 'howl' # <%= ENV['FLUXCO_DE_DEV_DB_USER'] || 'postgres' %>
  password: 'welovebubbles' # <%= ENV['FLUXCO_DE_DEV_DB_PASSWORD'] %>

  # Connect on a TCP socket. Omitted by default since the client uses a
  # domain socket that doesn't need configuration. Windows does not have
  # domain sockets, so uncomment these lines.
  host: <%= ENV['FLUXCO_DE_DEV_DB_HOST'] || 'localhost' %>

  # The TCP port the server listens on. Defaults to 5432.
  # If your server runs on a different port number, change accordingly.
  port: 3306 # <%= ENV['FLUXCO_DE_DEV_DB_PORT'] || '5432' %>

  # Schema search path. The server defaults to $user,public
  #schema_search_path: myapp,sharedapp,public

  # Minimum log levels, in increasing order:
  #   debug5, debug4, debug3, debug2, debug1,
  #   log, notice, warning, error, fatal, and panic
  # Defaults to warning.
  #min_messages: notice

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test: &test
  adapter: mysql2
  encoding: utf8

  database: <%= ENV['FLUXCO_DE_TEST_DB_DATABASE'] || 'fluxco_de_test' %><%= ENV['TEST_ENV_NUMBER'] %>
  pool: 5
  username: 'howl' # <%= ENV['FLUXCO_DE_TEST_DB_USER'] || 'postgres' %>
  password: 'welovebubbles' # <%= ENV['FLUXCO_DE_TEST_DB_PASSWORD'] %>
  host: <%= ENV['FLUXCO_DE_TEST_DB_HOST'] || 'localhost' %>
  port: 3306 # <%= ENV['FLUXCO_DE_TEST_DB_PORT'] || '5432' %>

production:
  adapter: mysql2
  encoding: utf8
  database: amoutreach_production
  pool: 5
  username: amoutreach
  password:
  host: <%= ENV['AMOUTREACH_PROD_DB_HOST'] || 'localhost'
  port: 3306

cucumber:
  <<: *test%